theme: jekyll-theme-hacker
#remote_theme: b2a3e8/jekyll-theme-console

robots: NOINDEX

# Site Settings
title                    : "vandenhoek.aero"
description              : &description "personal pages" # shows as subtitle
url                      : https://vandenhoek.aero # the base hostname
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "mvdhoek/mvdhoek.github.io"
teaser                   :  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
breadcrumbs              : false # true, false (default)
words_per_minute         : 160
future                   : true
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
talkmap_link             : false #change to true to add link to talkmap on talks page
atom_feed:
  path                   : # blank (default) uses feed.xml

# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Europe/Amsterdam # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Disable the "View on Github" button
github:
  is_project_page: false
