title: "showcase"
description: "Photography showcase."
url: "https://vandenhoek.aero"
baseurl: ""
timezone: Europe/Amsterdam
markdown: kramdown
permalink: pretty
robots: "noindex, nofollow, noarchive, nosnippet, noimageindex"
googlebot: "noindex, nofollow, noarchive, nosnippet, noimageindex"
