title: vandenhoek.aero
lang: nl

#theme: jekyll-theme-hacker
remote_theme: b2a3e8/jekyll-theme-console

header_pages:
  - index.md
  - about.md

style: dark # dark (default), light or hacker
listen_for_clients_preferred_style: false # false (default) or true

footer: 'follow us on <a href="https://twitter.com/xxx">test</a>'

robots: NOINDEX
