title: "Fullscreen Slider"
description: "Jekyll homepage with a fullscreen sliding image hero."
url: "https://vandenhoek.aero"
baseurl: ""
timezone: Europe/Amsterdam
markdown: kramdown
permalink: pretty
