theme: jekyll-theme-hacker
#remote_theme: b2a3e8/jekyll-theme-console

robots: NOINDEX

# Site Settings
title                    : "vandenhoek.aero"
description              : &description "Personal repository" # shows as subtitle
url                      : https://vandenhoek.aero # the base hostname
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "mvdhoek/mvdhoek.github.io"
teaser                   : # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"
#breadcrumbs              : true # true, false (default)
words_per_minute         : 160
#future                   : true
read_more                : "disabled" # if enabled, adds "Read more" links to excerpts
talkmap_link             : false #change to true to add link to talkmap on talks page
#atom_feed:
#  path                   : # blank (default) uses feed.xml

# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Europe/Amsterdam # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Header
header_pages:
  - index.md
  - about.md
  
style: dark
listen_for_clients_preferred_style: false

footer: 'vandenhoek.aero'

robots: noindex

# Page navigation
#navigation:
#  - text: Home
#    url: /
#  - text: About
#    url: /about/
